### ISSUE TITLE
Not connecting to the game

### ISSUE THREAD

**Issue by ghost** [ldmnt/ash-practice#1]
I extracted the .zip file, booted up the .exe and ran A Short Hike.
Then I ticked always on top and clicked attach.
All of the counters are just at zero

**Comment by ldmnt** [comment]
Hi, are you running the latest version of the game (1.9) ?
If so, this is normal, I have not updated this program recently and it will not work with recent versions of the game.

**Comment by ghost** [comment]
Okay, thanks for helping!
